name: CI

on: 
  push:
    branches: ['master']


jobs: 
  build: 
    steps: 
     - uses: actions/checkout@v1
       - name: npm install
         run: |
           npm install
       - name: npm start
        run: |
          npm start

          