name: Build and deploy React App to Localhost

on: 
  push:
    branches: ['master']


jobs: 
  build-and-deploy: 
    name: Build and Deploy
    runs-on: ubuntu-latest
    env: 
      BUCKET: http://localhost:8000/
      DIST: build

    steps:
    - uses: actions/checkout@v1
    - name: npx serve
      run: |
        npx serve